### ISSUE TITLE
RedisAppender should be asynchronous

### ISSUE THREAD

**Issue by GuiSim** [kmtong/logback-redis-appender#13]
Currently, logs written to the RedisAppender are sent using the same thread as the one that called the logger.

This can lead to issues if the Redis server is down, if there is unexpected network latency or any other delay in communication.

If there are no plans to change this behavior, I suggest that the documentation clearly states this. The documentation should also refer users to logback's [AsyncAppender](http://logback.qos.ch/manual/appenders.html#AsyncAppender) and highly recommend its usage.

Thanks!

**Comment by kmtong** [comment]
Thanks for the comments.  I would look into it once I have time.

**Comment by kmtong** [comment]
AsyncAppender is cool.  Included some hints in the README.  Thanks.
