### ISSUE TITLE
Support for MDC lookup in tags

### ISSUE THREAD

**Issue by prakashbalaji** [kmtong/logback-redis-appender#8]
Hello,

We are exploring to see if we could use logback-redis-appender to collect logs from 20+ micro services to single location. Most of the feature we need are already baked in but were wondering if there was support to lookup tags from MDC property map.
For example - 

```
<tags>
      ${request_id}
</tags>
```

Where request_id is set in the MDC map. We need the value of request_id to be added to the json tags field. 

Thanks

**Comment by kmtong** [comment]
This is an interesting idea.  I would look into it.

**Comment by kmtong** [comment]
Released 1.1.1

**Comment by prakashbalaji** [comment]
Thank you for the quick turn around...much appreciated.
