### ISSUE TITLE
Set testOnBorrow on JedisPool to true

### ISSUE THREAD

**Issue by jontejj** [kmtong/logback-redis-appender#9]
Sometimes if you use haproxy or other proxies in the middle of the connection towards redis, the proxy time outs the client. This leads to nasty error/warning messages being logged. Setting testOnBorrow on GenericObjectPoolConfig in RedisAppender solves this by validating the connection when a new one is pulled from the pool.

**Comment by kmtong** [comment]
Fixed in version 1.1.2.

**Comment by jontejj** [comment]
Wow! Thanks for such a fast release:)
